export const PROPERTY_SEARCH_QUERY_MAX_LENGTH = 1000;

export const PROPERTY_SEARCH_LOCATION_MAX_LENGTH = 100;

export const PROPERTY_SEARCH_PROPERTY_FLAGS_MAX_LENGTH = 1000;

export const PROPERTY_SEARCH_NUMBER_OF_ROOMS_MAX_LENGTH = 3;

export const PROPERTY_SEARCH_SQUARE_METERS_MAX_LENGTH = 5;

export const PROPERTY_SEARCH_PRICE_MAX_LENGTH = 10;
