export const PROPERTY_SEARCH_QUERY_MAX_LENGTH = 1000;

export const PROPERTY_SEARCH_LOCATION_MAX_LENGTH = 100;

export const PROPERTY_SEARCH_PROPERTY_FLAGS_MAX_LENGTH = 1000;

export const PROPERTY_SEARCH_NUMBER_OF_ROOMS_MAX_LENGTH = 3;

export const PROPERTY_SEARCH_SQUARE_METERS_MIN = 0;

export const PROPERTY_SEARCH_SQUARE_METERS_MAX = 100_000;

export const PROPERTY_SEARCH_PRICE_MIN = 0;

export const PROPERTY_SEARCH_PRICE_MAX = 10_000_000_000;

export const PROPERTY_SEARCH_FROM_MIN = 0;

export const PROPERTY_SEARCH_SIZE_MIN = 0;

export const PROPERTY_SEARCH_SIZE_MAX = 100;
